### ISSUE TITLE
Downgrade to Svelte 4

### ISSUE THREAD

**Issue by henil0604** [henil0604/japi#21]
# Situation

I’ve been thinking about the current situation with Svelte 5 and want to suggest downgrading to Svelte 4. A lot of the important libraries I use aren’t compatible with Svelte 5 yet, causing issues like broken features and unsustainable workarounds (for example, svelte-legos doesn't support Svelte 5 right now). Svelte 4 has been around longer and has a more stable ecosystem. It’s better-tested, and the community is larger, which means more resources and support. I’ve spent a lot of time fixing compatibility issues with Svelte 5, which has slowed down progress on actual feature development. Switching to Svelte 4 will help focus more on building and improving the app instead of dealing with these problems. Sticking with Svelte 5 without full library support is risky for the project’s stability and future upgrades. Using Svelte 4 will help avoid these risks and ensure a smoother development process.

----

I’ll look into this further and make a decision that works best.

**Comment by henil0604** [comment]
changes have been merged by #22
The issue remains open until further suggestions from @ardentkilnfire

**Comment by ardentkilnfire** [comment]
yeah, svelte 5 is nearly stable, but many other libraries / packages don't support it yet. So its reasonable to move to svelte 4 :smile:

**Comment by henil0604** [comment]
yea... closing this.
